# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build Disaster Alleviation Foundation/Disaster Alleviation Foundation.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'DisasterAlleviationFoundation1 - Azure'
    appType: 'webApp'
    WebAppName: 'DisasterAlleviationFoundation1'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'

